# cirkit_unit03:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50    

# Wheel & Steer (rocker_bogie_controller should be used without namespace)
steer_drive_controller:
    type        : "steer_drive_controller/SteerDriveController"
    rear_wheel  : 'base_to_wheel'
    front_steer : 'base_to_steer'
    rear_wheels : ['base_to_right_rear_wheel', 'base_to_left_rear_wheel']
    # TODO: front_wheels は完全gazebo用．実機と共通にする場合は削除するべき．要相談．
    front_wheels: ['base_to_right_front_wheel', 'base_to_left_front_wheel']
    front_steers: ['base_to_right_front_steer', 'base_to_left_front_steer']
    publish_rate: 100

    pose_covariance_diagonal : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wheel_separation_multiplier: 1.3
    wheel_separation_h_multiplier : 2.0
    wheel_radius_multiplier    : 0.5
    steer_pos_multiplier       : 0.7
    cmd_vel_timeout: 20
    base_frame_id: base_link

    enable_odom_tf: true
    #wheel_separation_w : 0.5
    #wheel_separation_h : 0.79
    wheel_radius : 0.28

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.9  # m/s
        min_velocity           : -0.9 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.7  # m/s^2
        min_acceleration       : -0.4 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2  #  wheel_right_front_joint_position_controller:
